# Generated by Django 5.1 on 2024-10-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('mobile_no', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked')], default='Active', max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
