# Generated by Django 5.1 on 2024-10-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='verification_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='verification_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
