# Generated by Django 5.1 on 2024-10-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_verification_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='verification_token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
