# Generated by Django 5.1 on 2024-11-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_users_is_active_remove_users_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='hh', max_length=30),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='hh', max_length=30),
        ),
    ]
