# Generated by Django 5.1 on 2025-05-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_users_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='modified_at',
        ),
    ]
