# Generated by Django 5.1 on 2024-11-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('FX', 'Fixed Amount'), ('PE', 'Percentage')], default='percent', max_length=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.IntegerField(),
        ),
    ]
