# Generated by Django 5.1 on 2024-11-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_alter_coupon_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
