# Generated by Django 5.1 on 2024-11-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
