# Generated by Django 5.1 on 2024-11-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_productvariant_productvarient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='total_quantity',
        ),
        migrations.AddField(
            model_name='productvarient',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
