# Generated by Django 5.1 on 2024-11-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_quantity_product_total_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarient',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
