# Generated by Django 5.1 on 2024-11-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_variant'),
        ('product', '0015_remove_productvarient_product_productvariant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVarient',
        ),
    ]
