# Generated by Django 5.1 on 2024-11-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_variant'),
        ('product', '0017_remove_productvariant_product_productvarient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
