# Generated by Django 5.1 on 2024-11-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_variant'),
        ('product', '0018_delete_productvariant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVarient',
            new_name='ProductVariant',
        ),
    ]
