# Generated by Django 5.1 on 2024-11-11 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0003_alter_address_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Mobile number must be 10 digits and start with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='pin_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='invalid_pin', message='PIN code must be 6 digits.', regex='^\\d{6}$')]),
        ),
    ]
