# Generated by Django 5.1 on 2024-11-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='max_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('product', 'Product'), ('brand', 'Brand'), ('category', 'Category')], default='product', max_length=10),
        ),
    ]
