# Generated by Django 5.1 on 2024-11-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_offer_max_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='max_discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
