# Generated by Django 5.1 on 2024-12-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_offer_max_discount_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='discount_value',
            new_name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_exclusive',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='max_discount_amount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_purchase_amount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_type',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='usage_limit',
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
