# Generated by Django 5.1 on 2024-12-10 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_category_unique_category_name_ci_and_more'),
        ('product', '0021_banner'),
        ('wallet', '0005_rename_discount_value_offer_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_name',
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='category.category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('Product', 'Product'), ('Category', 'Category')], default='Product', max_length=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='product.product'),
        ),
    ]
