# Generated by Django 5.1 on 2024-11-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
