# Generated by Django 5.1 on 2024-11-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='note_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
