# Generated by Django 5.1 on 2024-11-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_note_admin_orderitem_admin_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Payment_Failed', 'Payment Failed'), ('Processing', 'Processing'), ('On_Hold', 'On Hold'), ('Shipped', 'Shipped'), ('On_the_Way', 'On the Way'), ('Out_for_Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled_by_Customer', 'Cancelled by Customer'), ('Cancelled_by_Admin', 'Cancelled by Admin'), ('Returned', 'Returned'), ('Refunded', 'Refunded')], default='Pending', max_length=24),
        ),
    ]
