# Generated by Django 5.1 on 2024-11-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('RP', 'Razor Pay'), ('PP', 'PayPal'), ('BT', 'Bank Transfer'), ('WP', 'Wallet Pay'), ('COD', 'Cash on Delivery')], max_length=4),
        ),
    ]
