# Generated by Django 5.1 on 2024-11-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_payment_status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Paid', 'paid'), ('Unpaid', 'unpaid'), ('Failed', 'failed'), ('Refunded', 'refunded'), ('Processing', 'processing')], default='pending', max_length=10),
        ),
    ]
