# Generated by Django 5.1 on 2024-11-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderitem_item_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_bill_generated',
            field=models.BooleanField(default=False),
        ),
    ]
