# Generated by Django 5.1 on 2024-12-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('RP', 'Razor Pay'), ('WP', 'Wallet Pay'), ('COD', 'Cash on Delivery')], max_length=4),
        ),
    ]
